### ISSUE TITLE
error: root manifest not found

### ISSUE THREAD

**Issue by RajDSS** [SwiftDocOrg/swift-doc#162]
I am getting this error while running the command:

`swift run swift-doc coverage /Users/raj/my_ios_project/project/Sources --output "cov.json"`

**Comment by mattt** [comment]
@RajDSS I don't have enough information to reproduce this. However, searching for this error message took me to [this SO thread](https://stackoverflow.com/questions/50754432/swift-build-on-terminal-throw-error-root-manifest-not-found/54574414), which makes me think that you're running `swift run swift-doc` outside of the `swift-doc` project directory. If you're just using it, I'd recommend installing `swift-doc` using Homebrew instead of building from source.
