### ISSUE TITLE
Github Pages : Page navigation and css not working with HTML generated by swift doc

### ISSUE THREAD

**Issue by arpanCode** [SwiftDocOrg/swift-doc#210]
Hi Team, 
First Thanks a lot for this awesome work. 

I am experiencing an issue with swift doc when I am trying to publish with Github Pages. 

As per Github docs, [https://docs.github.com/en/enterprise-server@2.20/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site](url)

I can add HTML content on **master/docs** path and mark that branch as a source for publishing content to the Github page. But Instead of loading the proper HTML page it's loading the page without CSS and navigation to subsequent pages also broken. 

I can say that is the same behavior we get when opening index.html without running a local server. 

Any example or reference on how we can publish doc generated by swift doc over swift pages would really help me a lot? 
(Note: Considering HTML format only)

Thanks in Advance!

**Comment by mattt** [comment]
@arpanCode I believe the problem is that you're specifying a `--base-url` of `./`, which would cause invalid references to the CSS file on pages other than the root index. Assuming that you're generating for your GitHub Pages at https://arpancode.github.io/intro/, you should pass that as the `--base-url` option instead.

**Comment by arpanCode** [comment]
@mattt  ThankYou so much!
I have modified the Github Action file and added base-url: https://arpancode.github.io/intro/. 
It working perfectly now.
