### ISSUE TITLE
Caching documentation

### ISSUE THREAD

**Issue by muizidn** [SwiftDocOrg/swift-doc#212]
Hello!

I have some questions :
1. Is it good practice to cache documentation? 
2. Is there any obstacles, drawbacks or difficulties to implement this feature?
3. What consideration should be taken to design this feature?

**Comment by MaxDesiatov** [comment]
Could you clarify what you mean by "documentation caching" here?

**Comment by muizidn** [comment]
Generate documentation faster by cache previous action and only regenerate changed files.

**Comment by mattt** [comment]
Thanks for clarifying, @muizidn. In order to determine what's changed between runs, `swift-doc` would have to reprocess all of the files anyway, so I wouldn't anticipate incremental builds to be significantly faster. Or, at least, there are other things we could do first that would have a greater impact, but wouldn't require as much engineering work.

**Comment by muizidn** [comment]
Awesome thanks!!
