### ISSUE TITLE
Adding possibility to ignore certain folders

### ISSUE THREAD

**Issue by dtamiazzo** [SwiftDocOrg/swift-doc#234]
Hi, 
I don't know if it's a feature that's already implemented, but I'd really like to be able to specify certain folders to ignore when creating the documentation. 
Specifically, I need to avoid creating documentations for the Pods I imported in my app.
It would be nice to be able to have a sort of gitignore equivalent, a list of folders to ignore in  an external file.

Thank you

**Comment by mattt** [comment]
@dtamiazzo The approach so far has been to pass subdirectory paths as inputs rather than the root directory of your project. For example, running `swift-doc generate ./MyApp/Sources` instead of `./MyApp` would ignore any source files in `./MyApp/Pods`.

That said, I think most people would like `Pods`, `Tests`, and other common directories to be similarly ignored. To that end, I opened #241. Let me know what you think!

**Comment by mattt** [comment]
Fixed by #241.
