### ISSUE TITLE
documented only some pods

### ISSUE THREAD

**Issue by khaledbohout2** [SwiftDocOrg/swift-doc#70]
hey, it worked for me and generated this html file which is probably 
documentation for some pods and third party libraries and can not find any of my classes (models, view , presenters) , i even searched for some code in the documentation and could not find it in my code

![image](https://user-images.githubusercontent.com/46874509/78962747-6519fe80-7af5-11ea-8f06-bdd8baff6d78.png)

**Comment by mattt** [comment]
Currently, documentation is generated for only public declarations (`public` or `open` modifiers). Assuming that you aren't embedding dependencies alongside your source files, I would recommend specifying a more specific path to exclude vendored code.

**Comment by khaledbohout2** [comment]
so i can not document the wole project ? if i want to document the whole project i will make standalone documentation for each class!? although i tried specifying a more specific path to exclude vendored code and did not find any thing in documentation folder , it is empty

**Comment by mattt** [comment]
You can indeed generate documentation for your whole project all at once; my point was that you'd probably want to limit to your own code, and not 3rd party dependencies (e.g. nothing in the `Pods` directory).

If documentation for your own classes aren't showing up, it's most likely because they aren't declared with `public` or `open` modifiers. By default, declarations have an implicit `internal` access level, and those aren't currently emitted by `swift-doc`.

For example, if you have a view controller, like:

```swift
/// Documentation for MyViewController
class MyViewController: UIViewController { ... }
```

You should make add a `public` access modifier:

```swift
/// Documentation for MyViewController
public class MyViewController: UIViewController { ... }
```

**Comment by mattt** [comment]
This feature is tracked by #72.
